### ISSUE TITLE
Problems with requirments.txt, OPS editable install doesn't work

### ISSUE THREAD

**Issue by gamdow** [opensbli/opensbli#1]
I think I have finally figured out a problem I have been having with installing OpenSBLI that results in the ops_translator module not being found. That is, the editable install of OPS doesn't work because the file structure doesn't match the setup.py file they use, but you are using the editable install (to select a particular revision?). I have been getting around the problem by installing the requirements manually. However, the problem does appear to be on their end, so I have forked their repo and made the necessary changes (https://github.com/gamdow/OPS). You may want to fork it also and require that fork instead (you could also fork a particular revision to remove that particular requirement).

Also, should requirements not be sympy==1.0 (rather than >=)?

**Comment by spjammy** [comment]
Thanks for the suggestion. Now OPS installation is removed from  requirements.txt (this should be installed manually by the user). 
Sympy V1.0 in requirements was corrected. Thanks for pointing this out.
