### ISSUE TITLE
Import error C99CodePrinter

### ISSUE THREAD

**Issue by addy419** [opensbli/opensbli#4]
Hi, I am a developer for OPS and was trying to run the newly developed OpenMP Offload backend on Taylor Green Vortex. But, I am unable to generate applications for opensbli with the error:
```
Generating the /wave/wave.py application.
Traceback (most recent call last):
  File "wave.py", line 3, in <module>
    from opensbli import *
  File "/home/dcs/cstjpm/opensbli/opensbli/__init__.py", line 1, in <module>
    from .core import *
  File "/home/dcs/cstjpm/opensbli/opensbli/core/__init__.py", line 1, in <module>
    from .opensblifunctions import *
  File "/home/dcs/cstjpm/opensbli/opensbli/core/opensblifunctions.py", line 10, in <module>
    from opensbli.utilities.helperfunctions import get_inverse_deltas
  File "/home/dcs/cstjpm/opensbli/opensbli/utilities/__init__.py", line 1, in <module>
    from .helperfunctions import *
  File "/home/dcs/cstjpm/opensbli/opensbli/utilities/helperfunctions.py", line 9, in <module>
    from opensbli.code_generation.opsc import rc
  File "/home/dcs/cstjpm/opensbli/opensbli/code_generation/__init__.py", line 2, in <module>
    from .opsc import *
  File "/home/dcs/cstjpm/opensbli/opensbli/code_generation/opsc.py", line 8, in <module>
    from sympy.printing.ccode import C99CodePrinter
ImportError: cannot import name C99CodePrinter
Generation of wave.py has failed.
```
I have sympy installed on my system:
```
Name: sympy
Version: 1.0
Summary: Computer algebra system (CAS) in Python
Home-page: http://sympy.org
Author: SymPy development team
Author-email: sympy@googlegroups.com
License: BSD
Location: /gpfs/home/dcs/cstjpm/.local/lib/python2.7/site-packages
Requires: mpmath
Required-by:
```
Is something missing here?

**Comment by dl11g11** [comment]
Can you try with SymPy version 1.1 instead and see if the error persists?

**Comment by addy419** [comment]
@dl11g11 Yes, that worked. Thank you.

**Comment by addy419** [comment]
@dl11g11 are there any tests to check if the generated output is correct?

**Comment by dl11g11** [comment]
Some of the example applications have reference data included for comparison with a Python plot script you can run after the simulation finishes (plot.py). For example: Sod_shock_tube, shu_osher, katzer_SBLI in the /apps directory. Other cases need more complex post-processing and/or long statistics gathering.

There is more information in the OpenSBLI journal paper: https://www.sciencedirect.com/science/article/abs/pii/S0010465521001752

**Comment by addy419** [comment]
@dl11g11 Thank you for the suggestion. I'll try to run those application, since I need to check the correctness of the Offloaded code.

Unfortunately, I am running OPS on a cluster. I'm not sure how I can plot the results from the headless cluster to my linux machine.

**Comment by dl11g11** [comment]
The plot scripts generate a pdf file of the simulation result which you can download to your machine and view. Otherwise, try 'xdg-open' on the cluster with X11 ssh forwarding enabled and it will open in the system viewer.
